comvert: complete overhaul
* change script to complete functional
* add skip check blacklist
* fix getting parameters when blacklist and local log enable
* fix script warning from shellcheck

Signed-off-by: Dede Dindin Qudsy <xtrymind@gmail.com>

diff --git a/comvert b/comvert
--- a/comvert
+++ b/comvert
@@ -9,154 +9,214 @@ SOURCE=$(pwd)
 INPUT="cbr"
 OUTPUT="cbz"
 
-## User Options
-while getopts s:i:o:f:l:b opt; do
-	case $opt in
-	s) # Source directory
-		SOURCE=$OPTARG
-		;;
-	i) # Input format
-		INPUT=$OPTARG
-		;;
-	o) # Output format
-		OUTPUT=$OPTARG
-		;;
-	f) # Only work one file
-		FILE=$OPTARG
-		;;
-	l) # Log suspicious files locally
-		LOCAL=true
-		;;
-	b) # Skip blacklist check
-		NO_BL=true
-		;;
-	esac
-done
-
-shift $((OPTIND - 1))
-
-## Define INPUT format
-if [ -z "$FILE" ]; then
-	COMIC="*.$INPUT"
-else
-	INPUT="${FILE#*.}" # Get INPUT type from file
-	FILE=$(basename "$FILE" .$INPUT) # Redefine the file
-	COMIC="$FILE.$INPUT"
-fi
-
-## Define OUTPUT format
-if [ "$OUTPUT" == "cbz" ]; then
-	FORMAT="zip"
-elif [ "$OUTPUT" == "cbt" ]; then
-	FORMAT="tar"
-elif [ "$OUTPUT" == "cb7" ]; then
-	FORMAT="7z"
-else
-	{ echo "+ Output format is not supported"; echo; exit 1; }
-fi
-
 ## Output Variables
 LOG="$TEMP/comvert.log"
 CACHE="$SOURCE/.cb_cache"
 
-## Sanity checks
-if [ ! -f "$BLIST" ];then
-	{ echo "+ Could not find the Blacklist"; exit 1; }
-fi
+# Enforces the value needed for two-part flags
+function enforce_value() {
+    [[ ${#} -lt 1 ]] && die "An additional value is needed for one of the flags passed to this script!"
+}
 
-if [ -f "$LOG" ];then
-	rm "$LOG" \
-		|| { echo "+ Error removing old log"; exit 1; }
-	touch "$LOG" 2>/dev/null \
-		|| { echo "+ Error writing log"; exit 1; }
-else
-	touch "$LOG" 2>/dev/null \
-		|| { echo "+ Error writing log"; exit 1; }
-fi
+# Prints an error and exits the script
+function die() {
+    echo "${1}"
+    exit
+}
 
-if [ -d "$CACHE" ]; then
-	rm -rf "$CACHE" \
-		|| { echo "+ Error removing old cache"; exit 1; }
-	mkdir "$CACHE" 2>/dev/null \
-		|| { echo "+ Error creating cache"; exit 1; }
-else
-	mkdir "$CACHE" 2>/dev/null \
-		|| { echo "+ Error creating cache"; exit 1; }
-fi
+# Gather parameters
+function parse_parameters() {
+    while [[ ${#} -ge 1 ]]; do
+        case ${1} in
+            # Skip blacklist check
+            "-b")
+                NO_BL=true ;;
 
-## Start Logging
-clear
-exec > >(tee "$LOG")
-echo "+ Working from $SOURCE"
-echo
+            # Only work one file
+            "-f")
+                shift && enforce_value "${@}"
 
-## Convert Loop
-find "$SOURCE" -name "$COMIC" | while read -r CBFILE; do
+                FILE=${1} ;;
 
-BASENAME=$(basename "$CBFILE" .$INPUT)
-DIRNAME=$(dirname "$CBFILE")
-NEWNAME="$BASENAME.$OUTPUT"
+            # Input format
+            "-i")
+                shift && enforce_value "${@}"
 
-echo "> Processing: $BASENAME"
-	cd "$CACHE"
+                INPUT=${1} ;;
 
-echo "-> Extracting"
-	7z x "$CBFILE" >/dev/null
+            # Log suspicious files locally
+            "-l")
+                LOCAL=true ;;
 
-echo "--> Scanning"
+            # Output format
+            "-o")
+                shift && enforce_value "${@}"
 
-## Scan the Blacklist
-if [[ -z ${NO_BL} ]]; then
-	while read -r CBSCAN; do
-		CBCRED=$(find -type f -iname "$CBSCAN")
-		if [ ! -z "$CBCRED" ]; then
-			rm "$CBCRED"
-			echo "--> Removed Blacklisted File"
-		fi
-	done < "$BLIST"
-fi
+                OUTPUT=${1} ;;
 
-## Scan for Suspicious files
-SUSP="$SOURCE/suspicious_files.txt"
-CBSCAN=$(find -type f -iname "[x-z]*")
-if [ ! -z "$CBSCAN" ]; then
-	echo "--> Suspicious files found!"
-	if [[ -n ${LOCAL} ]]; then
-		echo "$BASENAME" >> "$SUSP"
-		echo "$CBSCAN" >> "$SUSP"
-		echo "|" >> "$SUSP"
-		echo "--> And logged to file"
+            # Source directory
+            "-s")
+                shift && enforce_value "${@}"
+
+                SOURCE=${1} ;;
+            *)
+                die "Invalid parameter" ;;
+        esac
+
+        shift
+    done
+}
+
+# Define INPUT format
+function def_input() {
+	if [ -z "$FILE" ]; then
+		COMIC="*.$INPUT"
 	else
-		echo "--> But not logged"
+		INPUT="${FILE#*.}" # Get INPUT type from file
+		FILE=$(basename "$FILE" ."$INPUT") # Redefine the file
+		COMIC="$FILE.$INPUT"
 	fi
-fi
+}
 
-echo "-> Compressing"
-	7z a -sdel -t$FORMAT "$NEWNAME" ./* > /dev/null
-	mv "$NEWNAME" "$DIRNAME"
+# Define OUTPUT format
+function def_output() {
+	if [ "$OUTPUT" == "cbz" ]; then
+		FORMAT="zip"
+	elif [ "$OUTPUT" == "cbt" ]; then
+		FORMAT="tar"
+	elif [ "$OUTPUT" == "cb7" ]; then
+		FORMAT="7z"
+	else
+		{ echo "+ Output format is not supported"; echo; exit 1; }
+	fi
+}
 
-## Dont delete the new file if it has the same name
-if [ "$INPUT" != "$OUTPUT" ]; then
-	rm "$CBFILE"
-fi
+# Sanity checks
+function sanity_check(){
+	if [ ! -f "$BLIST" ];then
+		{ echo "+ Could not find the Blacklist"; exit 1; }
+	fi
 
-echo "> Complete"
-echo
-done
+	if [ -f "$LOG" ];then
+		rm "$LOG" \
+			|| { echo "+ Error removing old log"; exit 1; }
+		touch "$LOG" 2>/dev/null \
+			|| { echo "+ Error writing log"; exit 1; }
+	else
+		touch "$LOG" 2>/dev/null \
+			|| { echo "+ Error writing log"; exit 1; }
+	fi
 
-echo "=> Conversion Done"
-rmdir "$CACHE"
-echo
+	if [ -d "$CACHE" ]; then
+		rm -rf "$CACHE" \
+			|| { echo "+ Error removing old cache"; exit 1; }
+		mkdir "$CACHE" 2>/dev/null \
+			|| { echo "+ Error creating cache"; exit 1; }
+	else
+		mkdir "$CACHE" 2>/dev/null \
+			|| { echo "+ Error creating cache"; exit 1; }
+	fi
+}
 
-## Stats
-CBDID=$(grep -c -i "Processing" "$LOG")
-CBFND=$(grep -c -i "Blacklisted" "$LOG")
-CBMSD=$(grep -c -i "Suspicious" "$LOG")
+# Scan the Blacklist
+function check_blacklist() {
+	if [[ -z ${NO_BL} ]]; then
+		while read -r CBSCAN; do
+			CBCRED=$(find . -type f -iname "$CBSCAN")
+			if [ ! -z "$CBCRED" ]; then
+				rm "$CBCRED"
+				echo "--> Removed Blacklisted File"
+			fi
+		done < "$BLIST"
+	fi
+}
 
-echo "+ $CBDID archives processed"
-echo "+ $CBFND files removed"
-echo "+ $CBMSD suspicious archives"
-echo
+# Scan for Suspicious files
+function check_suspicious() {
+	SUSP="$SOURCE/suspicious_files.txt"
+	CBSCAN=$(find . -type f -iname "[x-z]*")
+	if [ ! -z "$CBSCAN" ]; then
+		echo "--> Suspicious files found!"
+		if [[ -n ${LOCAL} ]]; then
+			{
+				echo "$BASENAME"
+				echo "$CBSCAN"
+				echo "|"
+			} >> "$SUSP"
+			echo "--> And logged to file"
+		else
+			echo "--> But not logged"
+		fi
+	fi
+}
 
-## Optionally Notify
-#notify-send Comvert "Sir, your comics are done"
+# Convert Loop
+function convert() {
+	find "$SOURCE" -name "$COMIC" | while read -r CBFILE; do
+
+		BASENAME=$(basename "$CBFILE" ."$INPUT")
+		DIRNAME=$(dirname "$CBFILE")
+		NEWNAME="$BASENAME.$OUTPUT"
+
+		echo "> Processing: $BASENAME"
+		cd "$CACHE" || die "folder is missing!"
+
+		echo "-> Extracting"
+		7z x "$CBFILE" >/dev/null
+
+		echo "--> Scanning"
+		check_suspicious
+		check_blacklist
+
+		echo "-> Compressing"
+		7z a -sdel -t$FORMAT "$NEWNAME" ./* > /dev/null
+		mv "$NEWNAME" "$DIRNAME"
+
+		## Dont delete the new file if it has the same name
+		if [ "$INPUT" != "$OUTPUT" ]; then
+			rm "$CBFILE"
+		fi
+
+		echo "> Complete"
+		echo
+		done
+}
+
+# Start Logging
+function start_log(){
+	clear
+	exec > >(tee "$LOG")
+	echo "+ Working from $SOURCE"
+	echo
+}
+
+function ending_info(){
+	echo "=> Conversion Done"
+	rmdir "$CACHE"
+	echo
+
+	## Stats
+	CBDID=$(grep -c -i "Processing" "$LOG")
+	CBFND=$(grep -c -i "Blacklisted" "$LOG")
+	CBMSD=$(grep -c -i "Suspicious" "$LOG")
+
+	echo "+ $CBDID archives processed"
+	echo "+ $CBFND files removed"
+	echo "+ $CBMSD suspicious archives"
+	echo
+}
+
+# Parse command line parameters and setup variable
+parse_parameters "${@}"
+def_input
+def_output
+
+# check environtment
+sanity_check
+
+# start convert
+start_log
+convert
+
+# print info
+ending_info
